### ISSUE TITLE
3.0.5 fails to build with -DENABLE_GTK_DOC=TRUE

### ISSUE THREAD

**Issue by heirecka** [libical/libical#390]
```
Scanning dependencies of target gtkdoc-libical-glib
make[2]: Leaving directory '/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build'
make -f doc/reference/libical-glib/CMakeFiles/gtkdoc-libical-glib.dir/build.make doc/reference/libical-glib/CMakeFiles/gtkdoc-libical-glib.dir/build
make[2]: Entering directory '/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build'
[ 98%] Generating libical-glib documentation
cd /var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/doc/reference/libical-glib && /usr/bin/gtkdoc-scan --module=libical-glib --deprecated-guards="LIBICAL_GLIB_DISABLE_DEPRECATED" --ignore-headers="libical-glib-private.h" --rebuild-sections --rebuild-types --source-dir="/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/src/libical-glib"
cd /var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/doc/reference/libical-glib && /usr/x86_64-pc-linux-gnu/bin/cmake -E chdir /var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/doc/reference/libical-glib /usr/x86_64-pc-linux-gnu/bin/cmake -E env LD_LIBRARY_PATH=":/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib:/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib:lib:" /usr/bin/gtkdoc-scangobj --module=libical-glib --cflags=\ -I/usr/x86_64-pc-linux-gnu/include/glib-2.0\ -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include\ -I/usr/x86_64-pc-linux-gnu/lib/libffi-3.2.1/include\ -Iinclude --ldflags=-L/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib\ -lical-glib\ -lglib-2.0\ -lgobject-2.0\ -L/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib\ -lical\ -Llib
[100%] Linking CXX executable regression
cd /var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/src/test && /usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/regression.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-c++  -march=native -O2 -pipe  -Wl,-O1 -Wl,--as-needed -rdynamic CMakeFiles/regression.dir/regression.c.o CMakeFiles/regression.dir/regression-component.c.o CMakeFiles/regression.dir/regression-classify.c.o CMakeFiles/regression.dir/regression-utils.c.o CMakeFiles/regression.dir/regression-recur.c.o CMakeFiles/regression.dir/regression-storage.c.o CMakeFiles/regression.dir/regression-cxx.cpp.o  -o regression -Wl,-rpath,/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib ../../lib/libicalvcal.so.3.0.5 ../../lib/libicalss_cxx.so.3.0.5 -lpthread /usr/x86_64-pc-linux-gnu/lib64/libicuuc.so -licui18n ../../lib/libicalss.so.3.0.5 ../../lib/libical_cxx.so.3.0.5 ../../lib/libical.so.3.0.5 /usr/x86_64-pc-linux-gnu/lib64/libicuuc.so -licui18n -lpthread 
make[2]: Leaving directory '/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build'
[100%] Built target regression
libical-glib-scan.o:libical-glib-scan.c:function output_signals: error: undefined reference to 'fopen'
libical-glib-scan.o:libical-glib-scan.c:function output_signals: error: undefined reference to '__errno_location'
libical-glib-scan.o:libical-glib-scan.c:function output_signals: error: undefined reference to 'fclose'
libical-glib-scan.o:libical-glib-scan.c:function compare_signals: error: undefined reference to 'strcmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signals: error: undefined reference to 'qsort'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'sprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strlen'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strncmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strncmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'sprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strlen'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strncmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strncpy'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strcmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strcmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strcmp'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'sprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strlen'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'sprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'strlen'
libical-glib-scan.o:libical-glib-scan.c:function output_object_signal: error: undefined reference to 'fprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_object_hierarchy: error: undefined reference to 'fopen'
libical-glib-scan.o:libical-glib-scan.c:function output_object_hierarchy: error: undefined reference to '__errno_location'
libical-glib-scan.o:libical-glib-scan.c:function output_object_hierarchy: error: undefined reference to 'fclose'
libical-glib-scan.o:libical-glib-scan.c:function output_hierarchy: error: undefined reference to 'fwrite'
libical-glib-scan.o:libical-glib-scan.c:function output_hierarchy: error: undefined reference to 'fprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_object_interfaces: error: undefined reference to 'fopen'
libical-glib-scan.o:libical-glib-scan.c:function output_object_interfaces: error: undefined reference to '__errno_location'
libical-glib-scan.o:libical-glib-scan.c:function output_object_interfaces: error: undefined reference to 'fclose'
libical-glib-scan.o:libical-glib-scan.c:function output_interfaces: error: undefined reference to 'fputs'
libical-glib-scan.o:libical-glib-scan.c:function output_interfaces: error: undefined reference to 'fprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_interfaces: error: undefined reference to 'fputc'
libical-glib-scan.o:libical-glib-scan.c:function output_interface_prerequisites: error: undefined reference to 'fopen'
libical-glib-scan.o:libical-glib-scan.c:function output_interface_prerequisites: error: undefined reference to '__errno_location'
libical-glib-scan.o:libical-glib-scan.c:function output_interface_prerequisites: error: undefined reference to 'fclose'
libical-glib-scan.o:libical-glib-scan.c:function output_prerequisites: error: undefined reference to 'fputs'
libical-glib-scan.o:libical-glib-scan.c:function output_prerequisites: error: undefined reference to 'fprintf'
libical-glib-scan.o:libical-glib-scan.c:function output_prerequisites: error: undefined reference to 'fputc'
libical-glib-scan.o:libical-glib-scan.c:function output_object_args: error: undefined reference to 'qsort'
2019-05-20 11:23:49,383:scangobj.py:execute_command:1196:WARNING:Linking scanner failed: 1, command: x86_64-pc-linux-gnu-ld libical-glib-scan.o -L/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib -lical-glib -lglib-2.0 -lgobject-2.0 -L/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build/lib -lical -Llib -o libical-glib-scan
make[2]: Leaving directory '/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build'
make[2]: *** [doc/reference/libical-glib/CMakeFiles/gtkdoc-libical-glib.dir/build.make:67: doc/reference/libical-glib/html/index.html] Error 1
make[1]: Leaving directory '/var/tmp/paludis/build/office-libs-libical-3.0.5/work/build'
make[1]: *** [CMakeFiles/Makefile2:1444: doc/reference/libical-glib/CMakeFiles/gtkdoc-libical-glib.dir/all] Error 2
make: *** [Makefile:144: all] Error 2
```

Looks like it needs to link to libc

**Comment by winterz** [comment]
please tell me which platform you are building on.
also, is this from the official tarballs or from a git clone?

**Comment by heirecka** [comment]
Exherbo Linux

https://github.com/libical/libical/archive/v3.0.5.tar.gz

**Comment by winterz** [comment]
perhaps you have LDFLAGS or CFLAGS set somehow to that is polluting the build?

**Comment by winterz** [comment]
is this a problem in libical 3.0.5 or not?
I'm not sure if I should close this.

**Comment by heirecka** [comment]
I'd say so, but I'm not really familiar with gtk-doc infrastructure.

CFLAGS are nothing out of the ordinary (-march=native -O2 -pipe) and if I remove --as-needed from LDFLAGS I still get the same result.

**Comment by winterz** [comment]
We just committed some fixes for building with gtk.  could you test?  both the master branch or the 3.0 branch have the fix.

**Comment by winterz** [comment]
3.0.6 was released today.
please test if this is fixed for you.

**Comment by heirecka** [comment]
Sorry for the late answer, but it still fails. Apparently the cmake module produces a wrong command line for ld:

```
[100%] Generating libical-glib documentation
cd /var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/doc/reference/libical-glib && /usr/bin/gtkdoc-scan --module=libical-glib --deprecated-guards="LIBICAL_GLIB_DISABLE_DEPRECATED" --ignore-headers="libical-glib-private.h" --rebuild-sections --rebuild-types --source-dir="/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/src/libical-glib"
cd /var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/doc/reference/libical-glib && /usr/x86_64-pc-linux-gnu/bin/cmake -E chdir /var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/doc/reference/libical-glib /usr/x86_64-pc-linux-gnu/bin/cmake -E env LD_LIBRARY_PATH=":/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/lib:/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/lib:lib:" /usr/bin/gtkdoc-scangobj --module=libical-glib --cflags=\ -I/usr/x86_64-pc-linux-gnu/include/glib-2.0\ -I/usr/x86_64-pc-linux-gnu/lib/glib-2.0/include\ -I/usr/x86_64-pc-linux-gnu/lib/libffi-3.2.1/include\ -Iinclude\ -march=native\ -pipe\ -O2\ -fvisibility=hidden\ -Wno-deprecated\ -Wall\ -Wno-unknown-pragmas\ -Wextra\ -Winit-self\ -Wunused\ -Wno-div-by-zero\ -Wundef\ -Wpointer-arith\ -Wtype-limits\ -Wwrite-strings\ -Werror=return-type\ -Wunused-but-set-variable\ -Wlogical-op\ -Wsizeof-pointer-memaccess\ -Wformat\ -Wformat-security\ -Wredundant-decls\ -D_XOPEN_SOURCE=500\ -D_DEFAULT_SOURCE\ -D_GNU_SOURCE --ldflags=\ -L/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/lib\ -lical\ -L/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/lib\ -lical-glib\ -Wl,-O1\ -Wl,--as-needed\ -lgobject-2.0\ -lglib-2.0\ -Llib

2019-11-01 21:10:44,722:scangobj.py:execute_command:1199:WARNING:Linking scanner failed: 1, command: x86_64-pc-linux-gnu-ld libical-glib-scan.o -L/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/lib -lical -L/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build/lib -lical-glib -Wl,-O1 -Wl,--as-needed -lgobject-2.0 -lglib-2.0 -Llib -o libical-glib-scan
make[2]: Leaving directory '/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/office-libs-libical-3.0.6/work/build'
x86_64-pc-linux-gnu-ld: unrecognized option '-Wl,-O1'
x86_64-pc-linux-gnu-ld: use the --help option for usage information
make[2]: *** [doc/reference/libical-glib/CMakeFiles/gtkdoc-libical-glib.dir/build.make:67: doc/reference/libical-glib/html/index.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:1534: doc/reference/libical-glib/CMakeFiles/gtkdoc-libical-glib.dir/all] Error 2
make: *** [Makefile:144: all] Error 2
```

**Comment by winterz** [comment]
no idea. must be a local configuration somehow
going on 2 years.
closing . reopen as needed
